name: Build release zip
on:
  push:
    tags: ["v*"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Build zip
        run: |
          plugin_dir=woo-contifico
          mkdir -p "$plugin_dir"
          rsync -av --exclude='.git*' --exclude='.github' --exclude='tests' ./ "$plugin_dir"/
          zip -r "${plugin_dir}.zip" "$plugin_dir"
      - uses: softprops/action-gh-release@v1
        with:
          files: woo-contifico.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
